In [2]:
# Write a NumPy program to create an array of 10 zeros.
import numpy as np
a = np.zeros(10)
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [3]:
# Write a NumPy program to create an array of 10 ones.
b = np.ones(10)
print(b)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [5]:
# Write a NumPy program to create a 3x3 matrix with values ranging from 0 to 8.
a1 = np.arange(0, 9).reshape(3, 3)
print(a1)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [6]:
# Write a NumPy program to reverse an array (first element becomes the last).
a2 = np.array([1,2,3,4,5,6])
np.flip(a2)

array([6, 5, 4, 3, 2, 1])

In [14]:
# Write a NumPy program to multiply two given matrices.
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])
print(np.dot(arr1, arr2))

70


In [12]:
arr3 = np.array([[1,2],[3,4]])
arr4 = np.array([[5,6],[7,8]])
arr5 = np.dot(arr3, arr4)
print(arr5)
print(type(arr5))


[[19 22]
 [43 50]]
<class 'numpy.ndarray'>


In [15]:
arr0 = np.array([[[1,2,3],[3,4,5],[6,7,8]]])
arrm = np.array([[[1,2,3],[3,4,5],[6,7,8]]])
print(np.dot(arr0, arrm))

[[[[ 25  31  37]]

  [[ 45  57  69]]

  [[ 75  96 117]]]]


In [1]:
# Write a NumPy program to create a 5x5 matrix with random values and find the minimum and maximum values.
import numpy as np
a = np.random.rand(5, 5)
print(a)
print(a.max())
print(a.min())

[[0.1046172  0.75386471 0.9290441  0.54165707 0.46688024]
 [0.32568671 0.9418477  0.56181707 0.46891944 0.02539362]
 [0.99156929 0.44326531 0.25561947 0.75783987 0.53030182]
 [0.54223575 0.82202102 0.11780877 0.18072715 0.47615321]
 [0.49846679 0.65311943 0.27039725 0.70172205 0.65588281]]
0.9915692875765412
0.02539362075845286


In [7]:
# Write a NumPy program to compute the sum of all elements, mean, and standard deviation of a given array.
arr0 = np.array([1,2,3,4,5,6,7])
print(np.sum(arr0))  # print sum

28


In [8]:
print(np.mean(arr0))  # print mean

4.0


In [9]:
print(np.std(arr0)) # print standard deviation

2.0


In [2]:
# Write a NumPy program to extract all odd numbers from an array.
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
odd_numbers = arr[arr % 2 != 0]
print("Original array:", arr)
print("Odd numbers:", odd_numbers)


Original array: [ 1  2  3  4  5  6  7  8  9 10]
Odd numbers: [1 3 5 7 9]
