In [2]:
# Write a NumPy program to create an array of 10 zeros.
import numpy as np
a = np.zeros(10)
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [3]:
# Write a NumPy program to create an array of 10 ones.
b = np.ones(10)
print(b)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [5]:
# Write a NumPy program to create a 3x3 matrix with values ranging from 0 to 8.
a1 = np.arange(0, 9).reshape(3, 3)
print(a1)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [6]:
# Write a NumPy program to reverse an array (first element becomes the last).
a2 = np.array([1,2,3,4,5,6])
np.flip(a2)

array([6, 5, 4, 3, 2, 1])